prompt: |
 Close up in-car shot of a rally driver during a rally race. The camera is rigidly mounted and locked to the vehicle and stays framed on the driver. 

 Behind the rally driver on the left is the black nomex racing seat and we can see the letter T and part of a letter O stitched on the upper headrest. 

 The driver wears deep blue rally racing gloves that enter frame as the driver controls the steering wheel.

 The driver looks ahead at the unseen road with intense focus and concentration as the car moves at incredible speed. 

 Outside the plexiglass window on the right overcast Corsican mountains rush past in a heavy motion blur. Inside the cabin it is dark compared to the bright environment outside. Light flickers in to the cabin from the right and front casting dynamic highlights and shadows inside. 
ref_prompt: |
 @image1 @video1
negative_prompt: cartoon, animated, fake, unrealistic, slow, low quality, unrealistic lighting, CGI, oversaturated, compression artifacts
start_image: nothing
start_image_720p: x:\urf_teaser2\shots\dvr\dvr_0016\startframe_grades\urf_dvr_0016_edit_v003.00114_00001_grade7_bal_high_protect_720p.png
start_image_1080p: 
reference_video: 
duration: 8